package com.bong;

import com.nice.pilot.pilot_rule.FBApplAddr;

declare FBApplAddr
    @role(event)
end


rule "EventCount 1"
when
	$oEvent : FBApplAddr( $orgId : org_id ) over window:length(1)
    accumulate( FBApplAddr(org_id == $orgId, $storeCd : store_cd) over window:time(10s); $stores : collectSet( $storeCd ); $stores.size() > 1 )
    //accumulate( FBApplAddr(org_id == $orgId) over window:time(10s); $cnt: count(1) ) 
then
    System.out.println("EventCount 1, " + $stores.size() + ", org_id : " + $orgId);
end
