package com.sample
 
import com.bong.Message;
import com.bong.NotEvent;
 
 
rule "exe"
when
    Message()
then
    System.out.println("stateless !!");
end
 
rule "EventCount"
when
    accumulate( $msg: Message(status == Message.HELLO); $cnt: count(1) ) 
then
    System.out.println("EventCount : " + $cnt);
end

rule "NotEventCount"
when
    accumulate( NotEvent( ) ; $cnt: count(1) ) 
then
    System.out.println("NotEventCount : " + $cnt);// 계속 증가함.
end
